export const GEOLOCATION = {
  RU: { name: 'Russia', flag: '🇷🇺', region: 'Europe' },
  SE: { name: 'Sweden', flag: '🇸🇪', region: 'Europe' },
  GB: { name: 'United Kingdom', flag: '🇬🇧', region: 'Europe' },
  PL: { name: 'Poland', flag: '🇵🇱', region: 'Europe' },
  PT: { name: 'Portugal', flag: '🇵🇹', region: 'Europe' },
  SI: { name: 'Slovenia', flag: '🇸🇮', region: 'Europe' },
  DE: { name: 'Germany', flag: '🇩🇪', region: 'Europe' },
  IT: { name: 'Italy', flag: '🇮🇹', region: 'Europe' },
  LT: { name: 'Lithuania', flag: '🇱🇹', region: 'Europe' },
  GR: { name: 'Greece', flag: '🇬🇷', region: 'Europe' },
  FI: { name: 'Finland', flag: '🇫🇮', region: 'Europe' },
  IS: { name: 'Iceland', flag: '🇮🇸', region: 'Europe' },
  AT: { name: 'Austria', flag: '🇦🇹', region: 'Europe' },
  FR: { name: 'France', flag: '🇫🇷', region: 'Europe' },
  RO: { name: 'Romania', flag: '🇷🇴', region: 'Europe' },
  MD: { name: 'Moldova', flag: '🇲🇩', region: 'Europe' },
  HU: { name: 'Hungary', flag: '🇭🇺', region: 'Europe' },
  NO: { name: 'Norway', flag: '🇳🇴', region: 'Europe' },
  MK: { name: 'North Macedonia', flag: '🇲🇰', region: 'Europe' },
  BG: { name: 'Bulgaria', flag: '🇧🇬', region: 'Europe' },
  ES: { name: 'Spain', flag: '🇪🇸', region: 'Europe' },
  CH: { name: 'Switzerland', flag: '🇨🇭', region: 'Europe' },
  HR: { name: 'Croatia', flag: '🇭🇷', region: 'Europe' },
  NL: { name: 'Netherlands', flag: '🇳🇱', region: 'Europe' },
  CZ: { name: 'Czechia', flag: '🇨🇿', region: 'Europe' },
  EE: { name: 'Estonia', flag: '🇪🇪', region: 'Europe' },

  US: { name: 'United States', flag: '🇺🇸', region: 'North America' },
  CA: { name: 'Canada', flag: '🇨🇦', region: 'North America' },

  BR: { name: 'Brazil', flag: '🇧🇷', region: 'South America' },
  AR: { name: 'Argentina', flag: '🇦🇷', region: 'South America' },
  CL: { name: 'Chile', flag: '🇨🇱', region: 'South America' },

  CN: { name: 'China', flag: '🇨🇳', region: 'Asia' },
  JP: { name: 'Japan', flag: '🇯🇵', region: 'Asia' },
  KR: { name: 'South Korea', flag: '🇰🇷', region: 'Asia' },
  ID: { name: 'Indonesia', flag: '🇮🇩', region: 'Asia' },
  IN: { name: 'India', flag: '🇮🇳', region: 'Asia' },
  HK: { name: 'Hong Kong', flag: '🇭🇰', region: 'Asia' },
  MY: { name: 'Malaysia', flag: '🇲🇾', region: 'Asia' },

  IL: { name:'Israel', flag: '🇮🇱', region: 'Asia' },
  TH: { name:'Thailand', flag: '🇹🇭', region: 'Asia' },
  QA: { name: 'Qatar', flag: '🇶🇦', region: 'Asia' },
  TR: { name: 'Turkey', flag: '🇹🇷', region: 'Asia' },
  VN: { name: 'Vietnam', flag: '🇻🇳', region: 'Asia' },
  TW: { name: 'Taiwan', flag: '🇹🇼', region: 'Asia' },
  OM: { name: 'Oman', flag: '🇴🇲', region: 'Asia' },
  SG: { name: 'Singapore', flag: '🇸🇬', region: 'Asia' },
  AE: { name: 'United Arab Emirates', flag: '🇦🇪', region: 'Asia' },
  KZ: { name: 'Kazakhstan', flag: '🇰🇿', region: 'Asia' },

  AU: { name: 'Australia', flag: '🇦🇺', region: 'Australia' },
}