export const OWN_INSTANCE_GEOLOCATION_MENU = [
  [['ALL WORLD', 'action:search:params:geolocation:select:any']],
  [['Europe', 'action:search:params:geolocation:select:europe']],
  [
    ['RU', 'action:search:params:geolocation:select:RU'],
    ['SE', 'action:search:params:geolocation:select:SE'],
    ['GB', 'action:search:params:geolocation:select:GB'],
    ['PL', 'action:search:params:geolocation:select:PL'],
    ['PT', 'action:search:params:geolocation:select:PT'],
    ['SI', 'action:search:params:geolocation:select:SI'],
    ['DE', 'action:search:params:geolocation:select:DE'],
    ['IT', 'action:search:params:geolocation:select:IT'],
  ],
  [
    ['LT', 'action:search:params:geolocation:select:LT'],
    ['GR', 'action:search:params:geolocation:select:GR'],
    ['FI', 'action:search:params:geolocation:select:FI'],
    ['IS', 'action:search:params:geolocation:select:IS'],
    ['AT', 'action:search:params:geolocation:select:AT'],
    ['FR', 'action:search:params:geolocation:select:FR'],
    ['RO', 'action:search:params:geolocation:select:RO'],
    ['MD', 'action:search:params:geolocation:select:MD'],
  ],
  [
    ['HU', 'action:search:params:geolocation:select:HU'],
    ['NO', 'action:search:params:geolocation:select:NO'],
    ['MK', 'action:search:params:geolocation:select:MK'],
    ['BG', 'action:search:params:geolocation:select:BG'],
    ['ES', 'action:search:params:geolocation:select:ES'],
  ],
  [
    ['CH', 'action:search:params:geolocation:select:CH'],
    ['HR', 'action:search:params:geolocation:select:HR'],
    ['NL', 'action:search:params:geolocation:select:NL'],
    ['CZ', 'action:search:params:geolocation:select:CZ'],
    ['EE', 'action:search:params:geolocation:select:EE'],
  ],
  [['North America', 'action:search:params:geolocation:select:north-america']],
  [
    ['US', 'action:search:params:geolocation:select:US'],
    ['CA', 'action:search:params:geolocation:select:CA'],
  ],
  [['South America', 'action:search:params:geolocation:select:south-america']],
  [
    ['BR', 'action:search:params:geolocation:select:BR'],
    ['AR', 'action:search:params:geolocation:select:AR'],
    ['CL', 'action:search:params:geolocation:select:CL'],
  ],
  [['Asia', 'action:search:params:geolocation:select:asia']],
  [
    ['CN', 'action:search:params:geolocation:select:CN'],
    ['JP', 'action:search:params:geolocation:select:JP'],
    ['KR', 'action:search:params:geolocation:select:KR'],
    ['ID', 'action:search:params:geolocation:select:ID'],
    ['IN', 'action:search:params:geolocation:select:IN'],
    ['HK', 'action:search:params:geolocation:select:HK'],
    ['MY', 'action:search:params:geolocation:select:MY'],
  ],
  [
    ['IL', 'action:search:params:geolocation:select:IL'],
    ['TH', 'action:search:params:geolocation:select:TH'],
    ['QA', 'action:search:params:geolocation:select:QA'],
    ['TR', 'action:search:params:geolocation:select:TR'],
    ['VN', 'action:search:params:geolocation:select:VN'],
  ],
  [
    ['TW', 'action:search:params:geolocation:select:TW'],
    ['OM', 'action:search:params:geolocation:select:OM'],
    ['SG', 'action:search:params:geolocation:select:SG'],
    ['AE', 'action:search:params:geolocation:select:AE'],
    ['KZ', 'action:search:params:geolocation:select:KZ'],
  ],
] as [string, string][][]